### ISSUE TITLE
onClick not working and throwing many errors

### ISSUE THREAD

**Issue by mark8044** [mu-dawood/fcm_config#24]
I can successfully get a local notification to show when a message comes in, but when I click on the notification in order to return back to the app, the onClick doesn't fire and I get all these errors:

```
E/flutter (18982): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FormatException: Unexpected end of input (at character 1)
E/flutter (18982): 
E/flutter (18982): ^
E/flutter (18982): 
E/flutter (18982): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1405:5)
E/flutter (18982): #1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:523:7)
E/flutter (18982): #2      _parseJson (dart:convert-patch/convert_patch.dart:41:10)
E/flutter (18982): #3      JsonDecoder.convert (dart:convert/json.dart:506:36)
E/flutter (18982): #4      JsonCodec.decode (dart:convert/json.dart:157:41)
E/flutter (18982): #5      jsonDecode (dart:convert/json.dart:96:10)
E/flutter (18982): #6      NotificationManager._onPayLoad (package:fcm_config/src/io_notifications_manager.dart:105:41)
E/flutter (18982): #7      AndroidFlutterLocalNotificationsPlugin._handleMethod (package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:459:32)
E/flutter (18982): #8      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:404:55)
E/flutter (18982): #9      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:397:34)
E/flutter (18982): #10     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:389:35)
E/flutter (18982): #11     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:386:46)
E/flutter (18982): #12     _invoke2.<anonymous closure> (dart:ui/hooks.dart:189:15)
E/flutter (18982): #13     _rootRun (dart:async/zone.dart:1428:13)
E/flutter (18982): #14     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (18982): #15     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (18982): #16     _invoke2 (dart:ui/hooks.dart:188:10)
E/flutter (18982): #17     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
E/flutter (18982): #18     _Channel.push (dart:ui/channel_buffers.dart:132:31)
E/flutter (18982): #19     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
E/flutter (18982): #20     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:544:22)
E/flutter (18982): #21     _dispatchPlatformMessage (dart:ui/hooks.dart:83:31)
E/flutter (18982): 
```

**Comment by mo-ah-dawood** [comment]
I need your notification payload to test with
